/// <reference types="vitest" />
import { defineConfig } from "vitest/config";
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    // This is the default configuration for all tests
    globals: true,
    environment: 'node', // Changed to node since we're testing utility functions, not React components
    include: ['tests/**/*.{test,spec}.{js,ts}'], // Only include tests in this package
    exclude: ['**/node_modules/**', '**/dist/**'],
    reporters: ['default', ['junit', { outputFile: 'artifacts/junit/unit-results.xml' }]],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: 'artifacts/coverage',
      // This is the updated, more robust exclusion pattern
      exclude: [
        '**/node_modules/**',
        '**/dist/**',
        '**/*.config.{ts,js}',
        '**/.pnpm/**',
        // Exclude all files in the public/build directory
        '**/apps/web/public/build/**',
        '**/apps/web/build/**',
        // Exclude problematic virtual files generated by Remix/Vite
        '**/build/server-assets-manifest:*',
        '**/build/server-entry-module:*',
        '**/@remix-run/**',
        // Exclude all virtual files with special characters
        '**/*@remix-run/**',
        '**/*:*',
        // Exclude all files outside of packages/shared
        '**/apps/**',
        '**/checkly.config.ts',
        '**/playwright.config.ts',
        // Only include our actual source files
        '!packages/shared/src/**',
      ],
    },
  },
});