name: QA Assessment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          # This line tells the action to install pnpm for you
          # It's a more reliable way to ensure pnpm is available.
          registry-url: 'https://registry.npmjs.org/'
          check-latest: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unit & API Tests
        run: pnpm test:unit && pnpm test:api

      - name: Run E2E Tests
        run: pnpm e2e:ci
        env:
          NODE_ENV: production

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            artifacts/junit
            artifacts/playwright-report
            
      - name: Upload E2E Test Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-traces
          path: artifacts/test-results
          retention-days: 1