name: QA Assessment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unit & API Tests
        run: pnpm test:unit && pnpm test:api
        # '&&' ensures fail-fast behavior. If unit tests fail, API tests won't run.

      - name: Run E2E Tests
        # Runs the E2E tests for all configured browsers in a matrix
        run: pnpm e2e:ci
        env:
          NODE_ENV: production
        # Playwright's test runner handles fail-fast.

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            artifacts/junit
            artifacts/playwright-report
            
      - name: Upload E2E Test Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-traces
          path: artifacts/test-results
          retention-days: 1