name: QA Assessment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Shared Package Tests
        run: npx vitest run packages/shared/tests --config packages/shared/vitest.config.ts --environment node

      - name: Run API Tests
        run: cd apps/api && npx vitest run --config vitest.config.ts

      - name: Run Web Component Tests
        run: cd apps/web && npx vitest run --config vitest.config.ts

      - name: Run E2E Tests
        run: npx playwright test --reporter=list,junit
        env:
          NODE_ENV: production

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            artifacts/junit
            artifacts/playwright-report
            
      - name: Upload E2E Test Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-traces
          path: artifacts/test-results
          retention-days: 1
